name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Backend)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./backend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

      - name: Build Project Artifacts (Backend)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./backend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

      - name: Deploy Project Artifacts to Vercel (Backend)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./backend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Frontend)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./frontend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

      - name: Build Project Artifacts (Frontend)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./frontend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

      - name: Deploy Project Artifacts to Vercel (Frontend)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        cwd: ./frontend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
